/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    Brush: typeof import('./components/Brush.vue')['default']
    BrushOptions: typeof import('./components/BrushOptions.vue')['default']
    CanvasNode: typeof import('./components/CanvasNode.vue')['default']
    DrawCanvas: typeof import('./components/canvas/DrawCanvas.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    ImageCanvas: typeof import('./components/canvas/ImageCanvas.vue')['default']
    MaskImage: typeof import('./components/canvas/MaskImage.vue')['default']
    PromptSection: typeof import('./components/PromptSection.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./components/Sidebar.vue')['default']
    Toolbar: typeof import('./components/Toolbar.vue')['default']
  }
}
